### ISSUE TITLE
Correct Database Connection

### ISSUE THREAD

**Issue by aeSzelag** [COSC481W-2024Fall/CampQuest#21]
User Story:
Dan, the remote worker looking for more outdoor time, wants to be able to pull up campsites on the web application.

Persona: Dan, the remote worker looking for more outdoor time
Feature: Being able to connect to the correct collection in the correct database
Business Value: Dan will be able to pull up campsites on CampQuest web app.

Tasks:
- [x] Load data into database collection on MongoDB
- [x] Load annotated data into test database collection on MongoDB
- [x] Correct database Connection (change from temp database on another MongoDB account to correct MongoDB account with Campsites database and testCampsites database)
- [x] Confirm connections with automated testing

Acceptance Tests:
1. The homepage should load the test data
2. If there is no data to return, the screen should return "No Campsites Found" rather than an error message.

Acceptance Criteria:
Database information, or no results message, will appear on working version of the web application, local and live.

Dependencies:
No Current Sprint PBIs are required to be completed to complete my tasks. 

Timeline: 
10/22/24-10/23/24: Correct database connection, load full data and test data, run local tests with Postman. 
10/24/24-10/28/24: Learn test automation with Mocha

**Comment by sjiang1** [comment]
1. In the title, you mentioned "connection error". Can you add an explanation for this error in the description?
2. Dependencies section is for "PBIs" or other related part. For example, do you need to wait on anything to start your work?
3. Please add labels to the issue, sprint-2
4. Please double-check if the timeline is correct (start date, and end date for this issue)
