### ISSUE TITLE
Add Search Feature, by Keyword, on Home Page

### ISSUE THREAD

**Issue by EvanMeyerEmich** [COSC481W-2024Fall/CampQuest#23]
# User Story:
As Jacob, a computer science student who loves camping, I want to search for campsites by entering keywords on the home page so that I can easily find campsites that match my interests, like those near water bodies or with specific features.

# Persona:
Jacob, a 21-year-old student, values campsites close to water bodies and prefers options that include modern comforts like showers. He frequently uses platforms such as Yelp, Reddit, and DNR for campsite information.

# Feature:
Implement a search functionality in the CampList component that allows users to filter campsites dynamically based on keywords typed in the search bar, specifically targeting campsite names.

# Business Value:
By enabling a quick and efficient way for users like Jacob to find campsites, the platform enhances user satisfaction and engagement. It simplifies the search process, making it intuitive and encouraging users to interact with the platform more frequently.

# Acceptance Criteria:
## Search Input:

- There is a search input box on the home page where users can type in keywords.
- Placeholder text in the search box reads “Search camps by name.”
## Matching Campsites Display:

- When the user enters a keyword, the app filters campsites whose names contain the keyword (case-insensitive).
- Search results display campsites that match the keywords in real-time as the user types.
- If no campsites match the search, display a message: “No camps available.”
## Search Result Layout:

- The matching campsites are displayed in the same grid format (3 campsites across) as all campsites.
- Ensure that the search results are mobile-friendly.
## Clear Search:

- Users can clear the search results and return to the full list of campsites by clearing the search input.
# Tasks:
## Frontend:

- Add a search input box to the CampList component.
- Implement a search handler that filters campsites dynamically as the user types, without needing backend changes.
- Style the search bar and ensure the layout remains responsive across different device sizes.
# Testing:

- Test the search input for case-insensitive keyword matches.
- Verify that clearing the search input resets the campsite list to the full set.
- Perform manual testing on both desktop and mobile views to ensure responsiveness and proper functionality.
### Scenario 1: Search by Keyword

- Given: The user is on the home page.
- When: The user types in a keyword in the search box.
- Then: Campsites with matching names should be displayed in real-time.
### Scenario 2: No Matching Campsites

- Given: The user types a keyword with no matching campsites.
- When: The search returns no matches.
- Then: The message “No camps available” should be displayed.
###  Scenario 3: Clear Search

- Given: The user has entered a search query.
- When: The user clears the search input.
- Then: The full list of campsites should be displayed again.
### Scenario 4: Mobile Responsiveness

- Given: The user is on a mobile device.
- When: The user performs a search.
- Then: The layout should adjust to display search results in a mobile-friendly grid.
Timeline:
Start Date: 10/16/2024
End Date: 10/16/2024

**Comment by sjiang1** [comment]
1. For the user story: please use the persona as your user
2. In general, for each user story, please list persona, feature, and business value.
3. Also, when you get the snapshot, please use a white background. Thanks!
4. Please add labels to the issue, sprint-2
5. Please double-check if the timeline is correct (start date, and end date for this issue)

**Comment by sjiang1** [comment]
Is it finished?

**Comment by sjiang1** [comment]
LOL. You are so quick. Is there a pull request related to it?

**Comment by EvanMeyer36** [comment]
@sjiang1 yes it was merged yesterday

**Comment by sjiang1** [comment]
Please link a pull request under "development" on the right side.
